// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtroIioSZH5ZTMNF-NOmVwUIXc-DjULPY',
    appId: '1:181774812098:android:4195533caf500b7aa1cc5b',
    messagingSenderId: '181774812098',
    projectId: 'todo-firebase-18c91',
    databaseURL: 'https://todo-firebase-18c91-default-rtdb.firebaseio.com',
    storageBucket: 'todo-firebase-18c91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9V3kenS8-yA--mv4HC35l9lwx6fgUl0c',
    appId: '1:181774812098:ios:dfb684f48e2abb05a1cc5b',
    messagingSenderId: '181774812098',
    projectId: 'todo-firebase-18c91',
    databaseURL: 'https://todo-firebase-18c91-default-rtdb.firebaseio.com',
    storageBucket: 'todo-firebase-18c91.appspot.com',
    iosBundleId: 'com.example.todoFire',
  );
}
